spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=label_printer;encrypt-false
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace